Homework3_Abramov
Darkfirs/pythonTP1 pull request #18
Opened 2023-10-10 16:50 UTC by Darkfirs

2023-10-12 17:40 UTC, toadharvard requested changes

2023-10-12 17:40 UTC, toadharvard commented on src/Homework/Homework3/Homework3_Abramov.py
> +    def ma_funct(arguments):
Че за название такое

2023-10-12 17:40 UTC, toadharvard commented on src/Homework/Homework3/Homework3_Abramov.py
> +        print("Отрицательная арность невозможна")
Почему не exception? Или хотя бы return

2023-10-12 17:40 UTC, toadharvard commented on src/Homework/Homework3/Homework3_Abramov.py
> +        print("Отрицательная арность невозможна")
Невозможна, но функция выполняется дальше. какой смысл?

2023-10-12 17:40 UTC, toadharvard commented on src/Homework/Homework3/Homework3_Abramov.py
> +        return lambda: function()
return function

2023-10-16 19:42 UTC, toadharvard requested changes

2023-10-16 19:42 UTC, toadharvard commented on src/Homework/Homework3/Homework3_Abramov.py
> +        sys.exit("Отрицательная арность невозможна")
Если выходишь из процесса, то зачем return 0?
Лучше написать raise ValueError("Отрицательная арность невозможна") и не нужно будет убивать процесс и выходить из функции

2023-10-16 19:42 UTC, toadharvard commented on src/Homework/Homework3/Homework3_Abramov.py
> +        return function()
Вызвал функцию, вместо возврата. Убери скобки

2023-10-16 19:42 UTC, toadharvard commented on src/Homework/Homework3/Homework3_Abramov.py
> +        sys.exit("Отрицательная арность невозможна")
Тут то же самое, что и выше

2023-10-16 19:43 UTC, toadharvard commented
А еще коммиты это не функции, НЕ НАДО ТУДА _ вставлять

2023-10-17 20:15 UTC, toadharvard commented
![image](https://github.com/Darkfirs/pythonTP1/assets/88928096/0997c9d0-426c-4681-8628-88b75bb987e4)
Wtf?

2023-10-17 20:16 UTC, toadharvard approved these changes

2023-10-19 13:28 UTC, SpirinEgor approved these changes

2023-10-19 13:28 UTC, merged